[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "PODImodels"
authors = [
    {name = "Shenhui_Ruan", email = "shenhui.ruan@kit.edu"}
]
description = "A py package to create ROM utilizing PODI method"
version = "0.0.4"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "scikit-learn",
    "scipy",
    "pyvista",
    "torch"
]

[dependency-groups]
dev = [
    "pytest",
    "foamToPython @ git+https://github.com/Ruansh233/foamToPython.git",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
